# Generated by Django 4.2.1 on 2023-05-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor", name="value", field=models.FloatField(default=0),
        ),
    ]
